-- patients table

INSERT INTO T_PATIENT(SURNAME, NAME, PATRONYMIC, PHONE_NUMBER) VALUES
('Соболев', 'Илья', 'Викторович', '+79874565656');
INSERT INTO T_PATIENT(SURNAME, NAME, PATRONYMIC, PHONE_NUMBER) VALUES
('Коняхин', 'Александр', 'Андреевич', '+79874565456');
INSERT INTO T_PATIENT(SURNAME, NAME, PATRONYMIC, PHONE_NUMBER) VALUES
('Заречняк', 'Юрий', 'Евгеньевич', '+79874545454');
INSERT INTO T_PATIENT(SURNAME, NAME, PATRONYMIC, PHONE_NUMBER) VALUES
('Кутузова', 'Елена', 'Владимировна', '+79874595958');
INSERT INTO T_PATIENT(SURNAME, NAME, PATRONYMIC, PHONE_NUMBER) VALUES
('Белов', 'Артем', 'Евгеньевич', '+79874858595');
INSERT INTO T_PATIENT(SURNAME, NAME, PATRONYMIC, PHONE_NUMBER) VALUES
('Шеюхин', 'Данил', 'Борисович', '+79874465123');

-- doctors table

INSERT INTO T_DOCTOR(SURNAME, NAME, PATRONYMIC, SPECIALIZATION) VALUES
('Коняхин', 'Андрей', 'Андреевич', 'Педиатр');
INSERT INTO T_DOCTOR(SURNAME, NAME, PATRONYMIC, SPECIALIZATION) VALUES
('Ковшов', 'Антон', 'Васильевич', 'Офтальмолог');
INSERT INTO T_DOCTOR(SURNAME, NAME, PATRONYMIC, SPECIALIZATION) VALUES
('Климова', 'Алена', 'Александровна', 'Терапевт');
INSERT INTO T_DOCTOR(SURNAME, NAME, PATRONYMIC, SPECIALIZATION) VALUES
('Шуткин', 'Игорь', 'Васильевич', 'Нейрохирург');
INSERT INTO T_DOCTOR(SURNAME, NAME, PATRONYMIC, SPECIALIZATION) VALUES
('Титов', 'Андрей', 'Васильевич', 'Уролог');
INSERT INTO T_DOCTOR(SURNAME, NAME, PATRONYMIC, SPECIALIZATION) VALUES
('Шеюхина', 'Евгения', 'Павловна', 'Гинеколог');
INSERT INTO T_DOCTOR(SURNAME, NAME, PATRONYMIC, SPECIALIZATION) VALUES
('Кутергин', 'Сергей', 'Витальевич', 'Хирург');

-- receipts table

INSERT INTO T_RECEIPT(PATIENT_ID, DOCTOR_ID, DESCRIPTION, CREATION_DATE, EXPIRE_DATE, PRIORITY) VALUES
(2, 4, 'Антигриппин', '2019-07-09', '2019-09-09', 'Немедленный');
INSERT INTO T_RECEIPT(PATIENT_ID, DOCTOR_ID, DESCRIPTION, CREATION_DATE, EXPIRE_DATE, PRIORITY) VALUES
(3, 7, 'Компресс', '1991-02-13', '1991-03-13', 'Нормальный');
INSERT INTO T_RECEIPT(PATIENT_ID, DOCTOR_ID, DESCRIPTION, CREATION_DATE, EXPIRE_DATE, PRIORITY) VALUES
(5, 4, 'Мирамистин', '2019-07-12', '2019-08-12', 'Срочный');
INSERT INTO T_RECEIPT(PATIENT_ID, DOCTOR_ID, DESCRIPTION, CREATION_DATE, EXPIRE_DATE, PRIORITY) VALUES
(6, 1, 'Виагра', '2019-07-12', '2019-08-12', 'Немедленный');
INSERT INTO T_RECEIPT(PATIENT_ID, DOCTOR_ID, DESCRIPTION, CREATION_DATE, EXPIRE_DATE, PRIORITY) VALUES
(1, 3, 'Морская соль', '2019-07-12', '2019-08-12', 'Нормальный');
